/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mylab;

public class Library {
	public static void main(String arg[]) {
		System.out.println("Hello, World!");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
